spring.application.name=CrawlTest_0808

spring.mvc.view.prefix=/WEB-INF/
spring.mvc.view.suffix=.jsp

spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true

#mybatis.mapper-locations=classpath:mapper/*.xml
#mybatis.type-aliases-package=com.kh.crawl.model